In [3]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [ ]:
pitches = []

In [7]:


for year in range(15, 19):
    for month in range(3, 12):
        if (year == 17 and month == 5) or (year == 18 and month == 5):
            pitches = pd.read_csv("pitchdata_" + str(month) + "_" + str(15) + "_" + str(year) + ".csv")

#pitches = pd.read_csv("pitchdata_3_18.csv", )

In [8]:
pitches.head()

,PITCHNO,TM_DATE,TM_TIME,PAOFINNING,PITCHOFPA,PITCHER,PITCHERID,PITCHERTHROWS,PITCHERTEAM,BATTER,...,Y0,Z0,VX0,VY0,VZ0,AX0,AY0,AZ0,GAMEID,PI_PITCH_TYPE
0,1,3/29/2018,2:40:39 PM,1,1,"Hamels, Cole",430935,Left,TEX,"Springer, George",...,50,6.006789,-5.541753,-128.595947,-6.365963,10.459448,26.621088,-20.135224,20180329-Arlington-1,FA
1,2,3/29/2018,2:40:53 PM,1,2,"Hamels, Cole",430935,Left,TEX,"Springer, George",...,50,5.944492,-4.349648,-128.311063,-5.468324,11.591063,26.985518,-19.898345,20180329-Arlington-1,SI
2,3,3/29/2018,2:41:08 PM,1,3,"Hamels, Cole",430935,Left,TEX,"Springer, George",...,50,6.090856,-6.886847,-131.290990,-4.949869,10.989218,27.924153,-19.328693,20180329-Arlington-1,FA
3,4,3/29/2018,2:41:52 PM,2,1,"Hamels, Cole",430935,Left,TEX,"Bregman, Alex",...,50,6.155188,-4.928870,-131.013212,-4.207840,9.092517,27.356660,-15.928903,20180329-Arlington-1,FA
4,5,3/29/2018,2:42:05 PM,2,2,"Hamels, Cole",430935,Left,TEX,"Bregman, Alex",...,50,5.995996,-7.951041,-131.121105,-5.956593,9.968671,28.417540,-15.240553,20180329-Arlington-1,FA